# site informaiotn
site_name: Example MKDoc Site
repo_url: https://github.com/dandange8005/mkdocs-site
repo_name: dandange8005/mkdocs-site
edit_uri: edit/main/docs/

# nav settings

# nav:
#   - Home: index.md
#   - Learning Central:
#     - Getting Started:


# theme settings
theme:
  name: material
  features:
    - navigation.tracking # URL updates as you scroll
    - navigation.tabs  # Top-level sections as tabs
    # - navigation.tabs.sticky # Sticky top-level sections
    - navigation.sections # Groups sections
    - navigation.indexes # Landing pages for sections. 
    - navigation.top # Top navigation
    - navigation.footer # Footer navigation
    - toc.follow # Table of contents follows as you scroll
    # - toc.integrate
    # - content.tabs.link
    - contend.code.annotate # Annotate code blocks
    - content.code.copy # Copy code blocks
    - content.action.edit # Edit page on GitHub
    # - content.action.view # View page source
    - search.highlight # Highlight search terms
    - search.suggest # Suggest search terms
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: indigo  

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
      accent: indigo

  font:
    text: Inter
    # code: Roboto Mono

# Extensions
markdown_extensions:
  - admonition # Information, warning, error, and tip boxes
  - attr_list # Attribute lists
  - footnotes
  - pymdownx.magiclink
  - pymdownx.details
  - md_in_html # Markdown in HTML
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search
  - roamlinks
  - git-revision-date-localized

# Additional CSS
extra_css:
  - stylesheets/extra.css

# Cookies
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
