site_name: This is my doc name
repo_url: https://github.com/dandange8005/mkdocs-test
repo_name: dandange8005/mkdocs-test
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    # - content.tabs.link
    - contend.code.annotate
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - content.action.view
    
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: purple
      accent: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: purple
      accent: teal

  font:
    text: Inter

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - footnotes
  - pymdownx.magiclink
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - roamlinks

extra_css:
  - stylesheets/extra.css